MODEL:
  META_ARCHITECTURE: "RetinaFace"
  BACKBONE:
    FREEZE_AT: 0 # No pretrained models provided / Do not freeze shadow layers
  ANCHOR_GENERATOR:
    SIZES: [[16, 32], [64, 128], [256, 512]]
  KEYPOINT_ON: True
  ROI_KEYPOINT_HEAD:
    MIN_KEYPOINTS_PER_IMAGE: 0    # Do not filter images by landmark
DATASETS:
  TRAIN: ("widerface_train",)
  TEST: ("widerface_train",)
DATALOADER:                                      
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.001  # Note that RetinaNet uses a different default learning rate
INPUT:
  MAX_SIZE_TRAIN: 840
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    SIZE: [0.3, 0.3]
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 840
TEST:
  KEYPOINT_OKS_SIGMAS: [1.0, 1.0, 1.0, 1.0, 1.0]
  DETECTIONS_PER_IMAGE: 2200
VERSION: 2
